### ISSUE TITLE
A Laya is not defined error was encountered while executing the script.

### ISSUE THREAD

**Issue by QuantumLeap-us** [demondvn/telegram-cat-game#1]
fetch('https://raw.githubusercontent.com/demondvn/telegram-cat-game/main/bundle.js').then(response => response.text()).then(script => eval(script));

Promise {<pending>}
VM242:47 Uncaught (in promise) ReferenceError: Laya is not defined
    at eval (eval at <anonymous> (k/:1:135), <anonymous>:47:21)
    at eval (eval at <anonymous> (k/:1:135), <anonymous>:9075:2)
    at <anonymous>:1:135

**Comment by demondvn** [comment]
this function on testing local, can't do at the same from another place.
